# Generated by Django 6.1.1 on 2026-09-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningenquiry',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approximate total trip budget.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='planningenquiry',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)')], default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='planningenquiry',
            name='travel_style',
            field=models.CharField(choices=[('budget', 'Budget-conscious'), ('comfortable', 'Comfortable'), ('premium', 'Premium'), ('luxury', 'Luxury')], default='comfortable', max_length=20),
        ),
        migrations.AddField(
            model_name='planningenquiry',
            name='travellers',
            field=models.PositiveIntegerField(default=1, help_text='Number of people travelling.'),
        ),
        migrations.AlterField(
            model_name='planningenquiry',
            name='travel_dates',
            field=models.CharField(blank=True, help_text='Rough dates, or "flexible".', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this review from the site without deleting it.'),
        ),
    ]
