# Generated by Django 6.1.1 on 2026-09-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_planningenquiry_budget_planningenquiry_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningenquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='planningenquiry',
            name='travel_dates',
            field=models.CharField(blank=True, help_text='Rough dates, or "flexible"', max_length=100),
        ),
    ]
