# Generated by Django 6.1.1 on 2026-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_planningenquiry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningenquiry',
            name='destination',
            field=models.CharField(blank=True, help_text='Where are you dreaming of?', max_length=100),
        ),
    ]
