# Generated by Django 6.1.1 on 2026-09-29 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_sitesettings_alter_planningenquiry_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='planning_enquiry',
            field=models.ForeignKey(blank=True, help_text='The planning enquiry this review is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='travel.planningenquiry'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for reviews added directly in the admin; set automatically for site submissions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
