# Generated by Django 6.1.1 on 2026-10-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Your Wanderwell Travel Proposal', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Introduction or summary of the proposed trip.', max_length=3000)),
                ('itinerary', models.TextField(blank=True, help_text='Day-by-day or general trip itinerary.', max_length=10000)),
                ('flight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accommodation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('activities_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, help_text='Wanderwell planning/service fee.', max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('changes_requested', 'Changes Requested'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional date and time when this proposal expires.', null=True)),
                ('customer_message', models.TextField(blank=True, help_text='Message from the customer when requesting changes.', max_length=3000)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.OneToOneField(help_text='Planning enquiry this proposal belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='travel.planningenquiry')),
            ],
            options={
                'verbose_name': 'Travel Proposal',
                'verbose_name_plural': 'Travel Proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
