# Generated by Django 6.1.1 on 2026-10-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_planningenquiryactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningEnquiryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transportation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('activities', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transfers', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='travel.planningenquiry')),
            ],
        ),
    ]
