# Generated by Django 6.1.1 on 2026-10-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_planningenquirypricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
