# Generated by Django 6.1.2 on 2026-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_proposal_sent_at_proposal_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('changes_requested', 'Changes Requested'), ('accepted', 'Accepted')], default='draft', max_length=30),
        ),
    ]
